# Generated by Django 5.2.1 on 2026-05-14 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_value', models.FloatField()),
                ('actual_value', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('ON_TRACK', 'ON_TRACK'), ('AT_RISK', 'AT_RISK'), ('OFF_TRACK', 'OFF_TRACK')], default='ON_TRACK', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='projects.project')),
            ],
        ),
    ]
